name: 'Commit Message Check'
on:
  [pull_request]

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Write PRs to file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: '/tmp/pr_json'
          contents: ${{ steps.get-pr-commits.outputs.commits }}
          write-mode: overwrite
  
      - name: Check for only one commit per PR
        run: |
          echo '${{ steps.get-pr-commits.outputs.commits }}' > /tmp/json
          echo "num_commits=$(jq '. | length' < /tmp/json)" >> $GITHUB_ENV
          [[ ${{ env.num_commits }} -eq 1 ]]
          
      - name: Must use valid commit prefix
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^(docs|test|chore|website|ci|infra|fix|feat):.*$'
          error: 'Commit message must lead with a prefix from: https://docs.dagger.io/1227/contributing#commit-messages. Use "feat: Add <package name> package" for new Universe packages.'
