name: CI/CD
on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dagger Prod Deploy
        uses: dagger/dagger-for-github@v2
        with:
          args: do -p ./jeremyprod deploy
        env:
          dagger_netlify_token: ${{ secrets.DAGGER_NETLIFY_TOKEN }}
